### ISSUE TITLE
New v5 API

### ISSUE THREAD

**Issue by benedeusz** [xplodwild/realmdefensecheat#17]
Game now works with v5 API.

I managed to debug few HTTP request with `mitmproxy`:
* no Hash field in HTTP headers
* HTTP Request and Response are encrypted and they are not in JSON format. `mitmproxy` doesn't detect data format

Seems like this package became outdated and won't work without improvements

**Comment by xplodwild** [comment]
Needs updating to the latest protocol, closing this issue, please follow progress in #25
