### ISSUE TITLE
App no longer working but I hope you will update - Willing to donate

### ISSUE THREAD

**Issue by Jeff2302** [xplodwild/realmdefensecheat#18]
Hi there, first of all thanks for developing the app for us players.

Today I discovered your app and was wondering if you are planning on updating it? I can't seem to get it to work and from another person's post, it seems like its because of the new update.

Hope you are considering updating your app. 
I would gladly contribute donations if needed.

**Comment by xplodwild** [comment]
Needs updating to the latest protocol, closing this issue, please follow progress in #25 

I added a donation link in the README if you wish to donate
