### ISSUE TITLE
No such host

### ISSUE THREAD

**Issue by BreezeFreeze** [xplodwild/realmdefensecheat#21]
I typed userid and added something, but it said Failed to load game data: lookup td-users2.babeltimeus.com: no such host. 

Is there any way to fix it?

**Comment by xplodwild** [comment]
I need to update it to the newer versions of the game. I'll do it when I have some time.

**Comment by matmalabat** [comment]
Thanks a lot xplodwild, you make great job !

**Comment by hunterpp** [comment]
Would appreciate, i too want my revenge on forever game play

**Comment by GimmeDatCode** [comment]
How can i help you find server?

**Comment by GimmeDatCode** [comment]
Ok did some packet inspection, server is changed to simply td-users.babeltimeus.com/v5 but when I try to add gems I get:

```
>>> add-gems 9999
Loading game data...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/xplodwild/realmdefensecheat/realmdefense.Unpad(0xc0001d4200, 0x0, 0x200, 0x200, 0xc0001d4200, 0x0)
	realmdefensecheat-master/src/github.com/xplodwild/realmdefensecheat/realmdefense/crypt.go:28 +0xe8

```

**Comment by BreezeFreeze** [comment]
> I need to update it to the newer versions of the game. I'll do it when I have some time.

Very nice, thanks a lot xplodwild !

**Comment by GimmeDatCode** [comment]
I hate this game so much. But like you I cannot stop the suffering. I've even given them money. And to end my suffering, I need more gems. And I would rather risk this cheat and get kicked off the platform....or better just have it work than continue on as I currently am. Guide me through the code, what is the first step to debugging this?

**Comment by Jax442** [comment]
Please update this :(

**Comment by GimmeDatCode** [comment]
ive officially put realm defense on my backburner. Was playing 4 realm sieges per day for the +100 gems. Did that for 2 months, drove me mad. Now just watching 3 ads per day. Happy to help debug or do any of the grunt work, just need a bit of a tutorial

**Comment by Jax442** [comment]
From what I understand there are two issues. 1) The key needs to be cracked again and 2) the api needs to be updated to v5. The main issue is the key mostly... which I'm not sure how he cracked, sucks I was late to the party and didnt get to use this :(

**Comment by xplodwild** [comment]
The explanations on how I reverse engineered the game are there: https://medium.com/@xplodwild/turning-the-frustration-of-a-mobile-game-into-a-reverse-engineering-training-a9887043efdf

I'm currently on vacations so I don't have all the tools on hand, but I'll sure give it a go when I'm back. Seeing all of you mad at them make me believe they didn't change their practices despite the devs themselves telling me directly they'd do better.

**Comment by Jax442** [comment]
Hey GimmieDatCode, if you're still playing I found a work around for now - it involves using an older version of the game where everything is unencrypted and then updating it afterwards once you've editted the gem/elixer values. If you can send me over a discord or twitter link I can explain in more detail.

**Comment by Jeff2302** [comment]
Hey Jax442
I would love to hear the method edit the gems/elixir using your method.

Twitter: Jeff2302 @JeffisAwsme

Would really appreciate it

**Comment by Jax442** [comment]
I decided to make a quick write up of the method instead, just be aware this will only work with a new account so you cant use your current one. I didn't mind it as I wasn't super far in the game. Until xplod has his way working I think this is the best alternative. 

You can see it here:
https://github.com/Jax442/realm-defense-gem-cheat

**Comment by Aiman-C** [comment]
@xplodwild Did you ever get round to trying it out again?

**Comment by RatihX** [comment]
@xplodwild Can you estimate when you will update the program?

Thanks and best regards

**Comment by Jax442** [comment]
Yeah would be nice but he doesn't seem to be very active these days. In the mean time the method I posted above still works if you want to try that out. Atleast until he comes out with a updated version

**Comment by RatihX** [comment]
I don't want to play through all worlds again tbh. Tried your solution and it worked but still not what I am looking for as I am too far in the game :)

**Comment by xplodwild** [comment]
Needs updating to the latest protocol, closing this issue, please follow progress in #25
