### ISSUE TITLE
New api version

### ISSUE THREAD

**Issue by mangacu** [xplodwild/realmdefensecheat#3]
Today, they update new version of API, can you help me find the algorithm for hash request & response value? I want to learn how to find that, thank you.

**Comment by xplodwild** [comment]
Hey! I updated the code and latest build with the new encryption API.
If you want to have more details about how it works to get this, make sure to read my articles about it:

- https://medium.com/@xplodwild/turning-the-frustration-of-a-mobile-game-into-a-reverse-engineering-training-a9887043efdf (part 1)
- https://medium.com/@xplodwild/reverse-engineering-of-a-mobile-game-part-2-they-updated-we-dumped-memory-27046efdfb85 (part 2)
