### ISSUE TITLE
Cant run the exe tool v1.1.1 in Windows 10 version 1803 1809

### ISSUE THREAD

**Issue by NicoTiing** [xplodwild/realmdefensecheat#4]
Hi,

After running the latest tool, I am getting this error, I also tries to run it in windows 7 in compatibility mode and run the tool as an admin.
![image](https://user-images.githubusercontent.com/26269631/52452921-03bc6f80-2b80-11e9-857e-60e8855c0f6b.png)

**Comment by xplodwild** [comment]
The file has been reuploaded (I built it for Linux instead of Windows, my bad)
