### ISSUE TITLE
Problemas con mi id

### ISSUE THREAD

**Issue by kakaruto33** [xplodwild/realmdefensecheat#5]
Disculpa pero no tengo idea de como obtener mi id soy nuevo en esto, por cierto si puedes hacer un vídeo de como usar la herramienta te lo agradecería mucho de antemano te doy las gracias por responder

**Comment by xplodwild** [comment]
Hello, I'm sorry I don't speak spanish. To get your ID, just go in the game's settings (Opciones), and below the Facebook button press "Contact" (Contactanos). This will generate an e-mail, but don't send it, just take note of the ID that has been pre-filled in the email.

Lazy Google Translate attempt:
Para obtener su identificación, simplemente vaya a la configuración del juego (Opciones), y debajo del botón de Facebook presione "Contactanos". Esto generará un correo electrónico, pero no lo envíe, solo tome nota de la ID que se ha completado previamente en el correo electrónico.
