### ISSUE TITLE
I do not idea

### ISSUE THREAD

**Issue by kakaruto33** [xplodwild/realmdefensecheat#6]
Hello apology run the file, I write my id and often write a command and I give enter but I automatically close the program is not to do

**Comment by notnilc** [comment]
> Hello apology run the file, I write my id and often write a command and I give enter but I automatically close the program is not to do

try passing your userid as a command line parameter

`cd /path/to/folder/containing/tool`
`RealmDefenseCheatTool.exe -userid <insert here your user id without the angle brackets>`
