### ISSUE TITLE
2.1.6 not working

### ISSUE THREAD

**Issue by darroj** [xplodwild/realmdefensecheat#9]
Updated the game version last night to 2.1.6 and it's no longer working. It can see the data of the save (ie you had 1306 elixir, now ...) But nothing is modifying. Thanks in advance for your help!

**Comment by xplodwild** [comment]
You must be doing something wrong, it is working fine for me here. Make sure you completely closed the game on your phone or tablet, so that it properly reloads the new save from the server.
